---
exclude: "^{{cookiecutter\\.project_name}}/"
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
        files: src
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-builtin-literals
        args: ["--no-allow-dict-kwargs"]
      - id: debug-statements

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.68.1
    hooks:
      - id: terraform_validate
      - id: terraform_checkov
        args:
          - --args=--no-guide
          - --args=--quiet
          - --args=--framework terraform
          - --args=--skip-check CKV_AWS_18,CKV_AWS_19,CKV_AWS_21,CKV2_AWS_34,CKV_AWS_50,CKV_AWS_115,CKV_AWS_116,CKV_AWS_117,CKV_AWS_144,CKV_AWS_145,CKV_AWS_173

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: src

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--max-line-length=101]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        language: python
        entry: detect-secrets-hook
        args: ["--baseline", ".secrets.baseline"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.4
    hooks:
      - id: python-safety-dependencies-check
        files: setup.py

  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - id: sign-commit
